```{r MARFIS_data}
# source("MARFIS_all in one.R")
# 
# # This is where we keep our MARFIS pulls
# file_path <- "R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata"
# 
# # Save the pull
# save(catch, didnotfish, licencerenewals, file = file_path)
# 
# # Load the pull
# load(file_path)
```

```{r get_scanned_licences}
# Load required libraries
library(stringr)
library(tidyverse)

# Set the parent folder that contains the scanned logs
parent_folder <- "R:/Science/Population Ecology Division/DFD/Alosa/Freshwater Fishing Logbooks/Logbook Scans/2024_FFLR_Scans_Gaspereau"

# Get all PDF file paths from the subfolders
pdf_files <- list.files(path = parent_folder, pattern = "\\.pdf$", recursive = TRUE, full.names = TRUE)

# Extract just the filename (not the full path)
file_names <- basename(pdf_files)

# Extract the 6-digit licence number at the beginning of the filename
licence_no <- str_extract(file_names, "^\\d{6}")

# Remove any NA values (filenames that don't start with 6 digits)
#licence_no <- na.omit(licence_no)

# Get unique licences
licence_no <- unique(licence_no)

```

```{r find_licences}
# Find the licences that have marfis data but no scans
catch |> 
  filter(YEAR == 2024) |> 
  distinct(LICENCE_ID) -> marfis_licences

marfis_licences |> 
  filter(!LICENCE_ID %in% licence_no) -> licences_missing_scans

licences_missing_scans

write_csv(licences_missing_scans, "C:/Users/graylo/Documents/missing_scans.csv")
```

