```{r, warning=FALSE}
require(ROracle)
library(tidyverse)

source("~/git/ALOSA.functions/functions/sourcery.R")

sourcery()

#Set account name, password, and server
channel <- dbConnect(
  DBI::dbDriver("Oracle"),
  oracle.username.GASP,
  oracle.password.GASP,
  "PTRAN",
  believeNRows = FALSE
  )
```


# Fishery data
```{r}
# Get the biocharacteristics data from the fishery for 2025
# We only want lengths of the fish that were aged from the fishery
read_csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2025/Ageing/GR fishery samples aged_LILY.csv") |> 
  arrange(sample) |> 
  pull(sample) -> fishery_ages

# Here we get the lengths of the fish that had their ages estimated and put them
# into the same bins we put the aged ladder fish into
read_csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2025/Gaspereau_fishingsites_biocharacteristics.csv") |> 
  filter(sample %in% fishery_ages) |> 
  mutate(DATE = make_date(year = year, month = month, day = day)) |> 
  mutate(DOY = yday(DATE)) |> 
  select(DATE, DOY, LOCATION = Location, SEX = sex, FORK_LENGTH = fork.length) |> 
  mutate(FORK_LENGTH = FORK_LENGTH * 10) -> fishery_lengths

# We need to make categories for length and summarise how many fish from the 
# fishery and the ladder were in each category. It looks like the aged fish from
# the fishery had a larger range of lengths than the aged fish from the ladder,
# so we will use the ranges observed in the fishery to determine the length bins
# as these same bins will also be used on the ladder fish.

# There is an error in the fishery lengths data
fishery_lengths[fishery_lengths$FORK_LENGTH == 2400, "FORK_LENGTH"] <- 240

# Now we can calculate the range of lengths to get some bins
length_range <- range(fishery_lengths$FORK_LENGTH)[2] - range(fishery_lengths$FORK_LENGTH)[1]
n_bins <- 10
bin_width <- length_range / n_bins

# Now we want to bin the fishery data
fishery_lengths |> 
  mutate(
    LENGTH_BIN = cut(
      FORK_LENGTH,
      breaks = seq(min(FORK_LENGTH, na.rm = TRUE), max(FORK_LENGTH, na.rm = TRUE) + bin_width, by = bin_width),
      right = FALSE
      )
    ) |>
  group_by(LENGTH_BIN, DOY, SEX) |>
  summarise(N = n(), .groups = "drop") |> 
  arrange(DOY, SEX, LENGTH_BIN) |> 
  select(DOY, LENGTH_BIN, SEX, N) -> fishery_lengths_binned

# Get the landings from the fishery for 2025 so we can use them to weight the
# binned length data from the fishery
fish_per_lb <- 0.227

# Get the landings for all three fishing sites and summarise for each DOY
read_csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2025/Gaspereau River 2025 fishery landings.csv") |> 
  mutate(DATE = make_date(year = year, month = month, day = day)) |> 
  mutate(DOY = yday(DATE)) |> 
  select(DATE, DOY, LOCATION = Location, LANDINGS = landings, UNIT = unit) |> 
  mutate(LANDINGS_FISH = if_else(UNIT == "lbs", LANDINGS * 2, LANDINGS / fish_per_lb)) |> 
  mutate(LANDINGS_FISH = round(LANDINGS_FISH)) |> 
  select(DATE, DOY, LOCATION, LANDINGS_FISH) |> 
  group_by(DOY) |> 
  summarise(LANDINGS_FISH = sum(LANDINGS_FISH)) -> fishery_landings

# Merge the binned fishery length data with the fishery landings data by DOY and
# multiply the number of fish observed in each bin by the number caught in that
# bin to get the number of fish total that fall into each length bin in the fishery
fishery_lengths_binned |> 
  group_by(DOY) |> 
  mutate(N_SUM = sum(N)) |> 
  mutate(N_PROP = N / N_SUM) |> 
  full_join(fishery_landings, by = "DOY") |> 
  mutate(TOTAL_FISH_IN_BIN = round(LANDINGS_FISH * N_PROP)) |> 
  select(DOY, LENGTH_BIN, SEX, N, TOTAL_FISH_IN_BIN) |> 
  drop_na() -> fishery_lengths_binned_totals

fishery_lengths_binned_totals

# Now we want to correct for the entire fishery since we only looked at three 
# sites. We know how many pounds total fish were reported as caught, so we can
# convert this to total fish caught and then get the proportion of total fish
# that these three stands represent

# Convert the total reported landings (from RM) in pounds to fish
total_landings <- 336873 * 2

# The LANDINGS_FISH column is in total fish, so if we sum it for all DOY and
# divide it by the total_landings, we will get the proportion of the fishery
# represented by the three sites
landings_corr <- sum(fishery_landings$LANDINGS_FISH) / total_landings

# If we divide by this, we will get the total fish for the whole fishery
fishery_lengths_binned_totals |> 
  mutate(FISHERY_CORRECTED = round(TOTAL_FISH_IN_BIN / landings_corr)) -> fishery_lengths_binned_totals_corrected

fishery_lengths_binned_totals_corrected
```

# Ladder biocharacteristics and binning

```{r}
# Get the age data from GR for 2025
# These data are weighted proportional to the run

# STEPS
# 1. We want to bin these data according to the bins for the fishery
fishery_lengths_binned_totals$LENGTH_BIN
ladder_bins <- levels(fishery_lengths_binned_totals$LENGTH_BIN)

length_breaks <- sort(unique(as.numeric(unlist(regmatches(ladder_bins, gregexpr("[0-9]+", ladder_bins)))))) # Thank you LLM-bot

# 2. We want to multiply by the ladder correction value to see what each bin of fish represents in total fish
ladd.corr <- 858041 / 500

get.age.data(2025, siteID = 3, sppID = 3501, AgeStructure = TRUE, PrimaryAger = "Y", channel) |> 
  mutate(
    DATE = make_date(year = YEAR, month = MON, day = DAY),
    DOY = yday(DATE),
    SEX = if_else(SEX_ID == 1, "M", "F"),
    FORK_LENGTH = FORK_LENGTH * 10
  ) |> 
  select(FISH_ID, DATE, DOY, SEX, FORK_LENGTH, WEIGHT) |> 
  mutate(
    LENGTH_BIN = cut(
      FORK_LENGTH,
      breaks = length_breaks,
      right = FALSE
    )
  ) |>
  group_by(DOY, LENGTH_BIN, SEX) |>
  summarise(N = n(), .groups = "drop") |>
  mutate(LADDER_CORRECTED = round(N * ladd.corr)) |>
  arrange(DOY, SEX, LENGTH_BIN) -> ladder_length_bins_totals_corrected

ladder_length_bins_totals_corrected
```

# Merge the fishery and ladder data
```{r}
# This is a sanity check to see the number of fish harvested versus the number
# escaped using the correction factors
fishery_lengths_binned_totals_corrected |> 
  full_join(ladder_length_bins_totals_corrected, by = c("DOY", "LENGTH_BIN", "SEX")) |> 
  ungroup() |> 
  summarise(FISHERY = sum(FISHERY_CORRECTED, na.rm = TRUE), LADDER = sum(LADDER_CORRECTED, na.rm = TRUE))

# This setup has all the data from both the fishry and the ladder, there are lots
# of NAs because there are missing length bins, days where sampling wasn't done
# at the fishery or ladder, etc 
fishery_lengths_binned_totals_corrected |>
  full_join(ladder_length_bins_totals_corrected, by = c("DOY", "LENGTH_BIN", "SEX")) |>
  group_by(DOY, LENGTH_BIN, SEX) |> 
  summarise(FISHERY = sum(FISHERY_CORRECTED, na.rm = TRUE), LADDER = sum(LADDER_CORRECTED, na.rm = TRUE)) |> 
  ungroup() |> 
  mutate(across(where(is.numeric), ~ na_if(.x, 0))) |> 
  mutate(
    TOTAL = FISHERY + LADDER,
    ER = round(FISHERY / TOTAL, 2),
    F_MORT = -log(1 - ER)
    ) |> 
  complete(DOY, LENGTH_BIN, SEX) |> 
  arrange(DOY, SEX, LENGTH_BIN)

# This is the dataframe but only where we have observations at the fishery AND 
# at the ladder so that we can get comparisons for ER
fishery_lengths_binned_totals_corrected |>
  inner_join(ladder_length_bins_totals_corrected, by = c("DOY", "LENGTH_BIN", "SEX")) |>
  group_by(LENGTH_BIN) |> 
  summarise(FISHERY = sum(FISHERY_CORRECTED, na.rm = TRUE), LADDER = sum(LADDER_CORRECTED, na.rm = TRUE)) |> 
  ungroup() |> 
  mutate(across(where(is.numeric), ~ na_if(.x, 0))) |> 
  mutate(
    TOTAL = FISHERY + LADDER,
    ER = round(FISHERY / TOTAL, 2),
    F_MORT = -log(1 - ER),
    # We get selectivity by comparing the F_MORT of all the length bins to the
    # length bin with the highest F_MORT which is going to be dependent on the
    # number of length bins
    SEL = F_MORT / max(F_MORT)
    )

```

```{r}
test <- get.age.data(2025, siteID = 3, sppID = 3501, AgeStructure = TRUE, PrimaryAger = "Y", channel)

test |> 
  group_by(CURRENT_AGE) |> 
  mutate(FORK_LENGTH = FORK_LENGTH * 10) |> 
  summarise(
    mean_length = mean(FORK_LENGTH, na.rm = TRUE),
    mean_weight = mean(WEIGHT, na.rm = TRUE)
    )
```

