---
title: "Gasp 2024 Tagging"
output: html_document
date: "2025-07-28"
---

```{r setup, include=FALSE}
#packages
require(lubridate)
require(dplyr)
require(tidyverse)
require(ROracle)
#source our functions
source("~/git/ALOSA.functions/functions/sourcery.R")
sourcery()
#connect to our database
channel=dbConnect(DBI::dbDriver("Oracle"), oracle.username.GASP, oracle.password.GASP, "PTRAN" , 
                  believeNRows=FALSE) 
```

```{r setup detections}
#need to use read_csv for dets because weird encoding
dets <- read_csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2024/PIT Downloads/Lanes mills exit_WORKING_1.csv")
metadata <- read.csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2024/PIT Downloads/2024 PIT Tagging Data.csv")

#clean detection data
# names(dets)[names(dets)=="TAGID"]<-"id"
# dets$date<-as.character(as.Date(dets$DATE, format = "%m/%d/%Y"))
# dets$time<-format(strptime(dets$time, format = "%H:%M.%OS"), "%H:%M:%OS")
# dets$dt<-ymd_hms(paste(dets$date, dets$time, sep = ""))
unique_dets <- unique(dets$id)

#clean metadata
metadata$id <- paste(metadata$pref, metadata$suff, sep="")
metadata$rdt <- ymd_hm(paste(metadata$rdate, metadata$rtime, sep = ""))
metadata$rdt[is.na(metadata$rdt)] <- paste(metadata$rdate[is.na(metadata$rdt)], "14:00:00", sep = " ") #for instance where release time wasn;t recorded.

#get rids of morts
metadata <- metadata[metadata$mort %in% "N",]

##how many tags for each tagger and ana?

MB <- metadata[metadata$tagger %in% "MB",]
GN <- metadata[metadata$tagger %in% "GN",]

ana <- metadata[metadata$ana %in% "Y",]
nana <- metadata[metadata$ana %in% "N",]
```

```{r tag detections summary}
#first, all tags (no treatment)
exit_all <- left_join(dets, metadata)
exit_all <- exit_all[exit_all$id %in% metadata$id,]

detected_all <- unique(exit_all$id)
length(metadata$id)
length(detected_all)

#now, ana
exit_ana <- exit_all[exit_all$id %in% ana$id,]
length(unique(exit_ana$id))
length(unique(ana$id))

#nana
exit_nana <- exit_all[exit_all$id %in% nana$id,]
length(unique(exit_nana$id))
length(unique(nana$id))

#Tagger
exit_gn <- exit_all[exit_all$id %in% GN$id,]
length(unique(exit_gn$id))
length(unique(GN$id))

exit_mb <- exit_all[exit_all$id %in% MB$id,]
length(unique(exit_mb$id))
length(unique(MB$id))
```

```{r migration timing}
exit_all$dt <- ymd_hms(paste(exit_all$date, exit_all$time, sep=""))
exit_all <- exit_all[exit_all$dt >= min(metadata$rdt),]

travel <- exit_all%>%
  group_by(id, tagger, ana)%>%
  summarize(swim = min(dt), rel = min(rdt), delay = swim-rel)%>%
  group_by(tagger)%>%
  summarize(mean = mean(delay), min = min(delay), max = max(delay), median = median(delay))

travel.times<- exit_all%>%
  group_by(id, tagger, ana)%>%
  summarize(swim = min(dt), rel = min(rdt), delay = swim-rel)

hist(as.numeric(travel.times$delay),breaks = 0:20)

#using median travel time, we get around 4 days for both taggers
```

```{r setup escapement counts}
#get escapement from both sites####
wrcount<-onespecies.river.escapement(fixtime = T,downstream.migration = F,year = 2024,
                                    database = T,site = 3,channel = channel)
#lm count data is already trimmed to the 21st of May, after which there is too much down stream migration
lmcount<-onespecies.river.escapement(filename="R:/Science/Population Ecology Division/DFD/Alosa/Locations/Gaspereau River/Gaspereau 2024/Lanes Mills 2024 count data.csv",
                                     fixtime = F,downstream.migration = F,year = 2024,
                                     database = F,site = 4,channel = channel)
# LM dates are may 5 to 21

#trim data
#using a travel time of 4 days, the window for WR is May 01 to May 17. 
#however, since we counted 0s at LM, we can conclude that all the fish that
#migrated up WR before May 01 didn't slip by LM, so let's include those fish 
wrcount.trim<-wrcount[wrcount$dayofyear<=138,]
metadata.trim<-metadata[metadata$rdt<"2024-05-20",]

```


```{r weight detections}
#weight fish based on release time####
#arbitrary attempt 1
#tag release days: "2024-05-03" "2024-05-06" "2024-05-08" "2024-05-13" "2024-05-14" "2024-05-15" "2024-05-16" "2024-05-17"
g1<-sum(wrcount.trim$total[wrcount.trim$dayofyear<=125]) #start to may 4
g2<-sum(wrcount.trim$total[wrcount.trim$dayofyear>=126 & wrcount.trim$dayofyear<=128])
g3<-sum(wrcount.trim$total[wrcount.trim$dayofyear>=129 & wrcount.trim$dayofyear<=131])
g4<-sum(wrcount.trim$total[wrcount.trim$dayofyear>=132 & wrcount.trim$dayofyear<=134])
g5<-sum(wrcount.trim$total[wrcount.trim$dayofyear==135])
g6<-sum(wrcount.trim$total[wrcount.trim$dayofyear==136])
g7<-sum(wrcount.trim$total[wrcount.trim$dayofyear==137])
g8<-sum(wrcount.trim$total[wrcount.trim$dayofyear==138])

n1<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-03",])
n2<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-06",])
n3<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-08",])
n4<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-13",])
n5<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-14",])
n6<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-15",])
n7<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-16",])
n8<-nrow(metadata.trim[metadata.trim$rdate=="2024-05-17",])

w1<-g1/nrow(metadata.trim[metadata.trim$rdate=="2024-05-03",])
w2<-g2/nrow(metadata.trim[metadata.trim$rdate=="2024-05-06",])
w3<-g3/nrow(metadata.trim[metadata.trim$rdate=="2024-05-08",])
w4<-g4/nrow(metadata.trim[metadata.trim$rdate=="2024-05-13",])
w5<-g5/nrow(metadata.trim[metadata.trim$rdate=="2024-05-14",])
w6<-g6/nrow(metadata.trim[metadata.trim$rdate=="2024-05-15",])
w7<-g7/nrow(metadata.trim[metadata.trim$rdate=="2024-05-16",])
w8<-g8/nrow(metadata.trim[metadata.trim$rdate=="2024-05-17",])

####scale detections to population, then back down to sample####
trimdet<-exit_all[exit_all$dt<"2024-05-21 23:59:59",]
tags.det<-unique(trimdet$id)

#number of tags detected in each period
d1<-length(unique(trimdet$id[trimdet$rdate=="2024-05-03"]))
d2<-length(unique(trimdet$id[trimdet$rdate=="2024-05-06"]))
d3<-length(unique(trimdet$id[trimdet$rdate=="2024-05-08"]))
d4<-length(unique(trimdet$id[trimdet$rdate=="2024-05-13"]))
d5<-length(unique(trimdet$id[trimdet$rdate=="2024-05-14"]))
d6<-length(unique(trimdet$id[trimdet$rdate=="2024-05-15"]))
d7<-length(unique(trimdet$id[trimdet$rdate=="2024-05-16"]))
d8<-length(unique(trimdet$id[trimdet$rdate=="2024-05-17"]))

#try with vectors
#tag release days: "2024-05-03" "2024-05-06" "2024-05-08" "2024-05-13" "2024-05-14" "2024-05-15" "2024-05-16" "2024-05-17"
g<-c(sum(wrcount.trim$total[wrcount.trim$dayofyear<=125]), #start to may 4
     sum(wrcount.trim$total[wrcount.trim$dayofyear>=126 & wrcount.trim$dayofyear<=128]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear>=129 & wrcount.trim$dayofyear<=131]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear>=132 & wrcount.trim$dayofyear<=134]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear==135]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear==136]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear==137]),
     sum(wrcount.trim$total[wrcount.trim$dayofyear==138])
)

n<-c(nrow(metadata.trim[metadata.trim$rdate=="2024-05-03",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-06",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-08",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-13",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-14",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-15",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-16",]),
     nrow(metadata.trim[metadata.trim$rdate=="2024-05-17",])
)

w<-g/n

####scale detections to population, then back down to sample####
trimdet<-exit_all[exit_all$dt<"2024-05-21 23:59:59",]
tags.det<-unique(trimdet$id)

#number of tags detected in each period
d<-c(length(unique(trimdet$id[trimdet$rdate=="2024-05-03"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-06"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-08"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-13"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-14"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-15"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-16"])),
     length(unique(trimdet$id[trimdet$rdate=="2024-05-17"]))
)

#scale each group up to the population
D<-d*w

#weighted number of detected tags, scaled back down to the sample size
dw<-sum(D)*sum(n)/sum(g)
dw<-D*n/g

#weighting this way results in only a corrected number of fish, losing the tagger/ana variables
#by running a blr on the data and adding rows for every fish in the population,
#we are assuming that there is no change in passage success as time goes on, and 
#a big fish on day has the same prob as a small fish at the end.
#so a blr where we just add all fish in as rows, essentially assumes that there
#is no change in passage success as time goes on.
#we could either check this assumption (maybe it will be revealed to be no big deal)
#by looking at fork lengths of tagged/untagged fish at WR
#demonstrate that the assumption doesn;t matter enough to account for (maybe do two prop ztest, show results are still significant)
#or figure out a way to do a weighted blr and weight the population somehow
#or use the weights to make a second "tagged" population to directly compare to the real population
#by adding a rows for each tagged fish equal to the weights
```

```{r binary logistic regression}
#demonstrate tagging effect with a binary logistic regression (blr)
#need to create a dataframe with a row for every fish in the population
#start by subsetting tag data
#using data trimmed only to the study window, for releases and detections
tag.df<-subset(metadata.trim,select=c(id,ana,tagger))
tag.df$pass.success<-ifelse(tag.df$id %in% trimdet$id,1,0)

#now, make a population dataframe
wrN<-round(sum(wrcount.trim$total),0) #number of fish that passed WR
lmN<-round(sum(lmcount$total),0) #number of fish that passed LM
failN<-wrN-lmN #number of fish that passed WR but not LM
pop.df<-data.frame(id=as.character(1:wrN),
                   tagger=rep("N",wrN),
                   ana=rep("N",wrN),
                   pass.success=c(rep(1,lmN),rep(0,failN))
)

#merge the two dataframes
all.df<-rbind(tag.df,pop.df)

#run model
fit1<-glm(pass.success~tagger*ana,data=all.df,family="binomial")
summary(fit1)

#model with no interaction
fit2<-glm(pass.success~tagger,data=all.df,family="binomial")
summary(fit2)
```

