```{r, warning=FALSE}
# Get the MARFIS data and clean it
source("~/git/ALOSA.functions/functions/sourcery.R")
sourcery()
#source("C:/Users/graylo/Documents/git/ALOSA.functions/other_functions/pull_marfis_data.R")
load("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata")
source("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/marfis_error_cleaner.R")

df <- marfis_error_cleaner(
  catch,
  convert_to_kgs = TRUE,
  tidy_data = TRUE,
  correct_eel_pot = TRUE,
  unknown_rivers_are_na = TRUE,
  unknown_gear_are_na = TRUE
  )

# dfens<-df[df$COUNTY %in% c("COLCHESTER COUNTY", "CUMBERLAND COUNTY", "HALIFAX COUNTY", "HANTS COUNTY", "GUYSBOROUGH COUNTY"),]
# dfenssum<-dfens[c(1,2,4)]
# dfenssum<-dfenssum[!duplicated(dfenssum),]
# table(dfenssum$RIVERNAME_CLEANED,dfenssum$YEAR)
# 
# dfcb<-df[df$COUNTY %in% c("RICHMOND COUNTY", "VICTORIA COUNTY", "CAPE BRETON COUNTY"),]
# dfcbsum<-dfcb[c(1,2,4)]
# dfcbsum<-dfcbsum[!duplicated(dfcbsum),]
# table(dfcbsum$RIVERNAME_CLEANED,dfcbsum$YEAR)
```


```{r}
# Select data from Eastern NS. We remove AVON from the rivers as it is in West Hants
df |> 
  filter(PROVINCE == "NS") |> 
  mutate(
    AREA = case_when(
      COUNTY %in% c("COLCHESTER COUNTY", "CUMBERLAND COUNTY", "HALIFAX COUNTY", "HANTS COUNTY", "GUYSBOROUGH COUNTY") ~ "Eastern NS",
      COUNTY %in% c("RICHMOND COUNTY", "VICTORIA COUNTY", "CAPE BRETON COUNTY") ~ "Cape Breton",
      TRUE ~ "Western NS"
    ),
    YEAR = as.factor(YEAR)
  ) |> 
  filter(!(RIVERNAME_CLEANED == "AVON")) |> 
  group_by(YEAR, AREA) |> 
  summarise(TOTAL = sum(FV_WEIGHT)) |> 
  filter(YEAR %in% c(2015:2025)) |> 
  ggplot(aes(YEAR, TOTAL, fill = AREA)) +
  geom_col(colour = "grey20", alpha = 0.8) +
  scale_fill_viridis_d(direction = 1) +
  labs(title = "Reported gaspereau landings in NS by area", x = "", y = "Landings (kg)", fill = "Area") +
  scale_y_continuous(labels = scales::comma, n.breaks = 10) +
  theme_bw() +
  theme(
      axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(size = 12),
      #axis.title.x = element_blank(),
      axis.title.y = element_text(size = 14),
      panel.grid = element_blank(),
      #panel.grid.minor = element_blank(),
      legend.background = element_blank(),
      # legend.position = "top",
      # legend.justification = "left",
      plot.title = element_text(size = 16),
      # plot.subtitle = element_text(size = 14)
    )

ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2026/ens/landings_by_area.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r}
ens_counties <- c("COLCHESTER COUNTY", "CUMBERLAND COUNTY", "HALIFAX COUNTY", "HANTS COUNTY", "GUYSBOROUGH COUNTY")

df |>
  filter(PROVINCE == "NS" & COUNTY %in% c(ens_counties)) |> 
  #filter(YEAR != 2025) |> 
  group_by(YEAR, COUNTY) |> 
  summarise(unique_licences = n_distinct(LICENCE_ID), .groups = "drop") -> ens_lics

ens_lics |> 
  #complete(COUNTY, YEAR) |> 
  mutate(
    YEAR = as.factor(YEAR),
    COUNTY = str_remove(COUNTY, " COUNTY"),
    COUNTY = str_to_title(COUNTY),
    COUNTY = fct_reorder(COUNTY, unique_licences, .desc = FALSE)
    ) |> 
  filter(YEAR %in% c(2015:2025)) |> 
  ggplot(aes(YEAR, unique_licences, fill = COUNTY)) +
  geom_col(colour = "grey20", alpha = 0.8) +
  scale_fill_viridis_d(direction = 1) +
  labs(title = "Gaspereau licences reporting in Eastern NS", x = "", y = "Licences", fill = "County") +
  theme_bw() +
  theme(
      axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(size = 12),
      #axis.title.x = element_blank(),
      axis.title.y = element_text(size = 14),
      panel.grid = element_blank(),
      #panel.grid.minor = element_blank(),
      legend.background = element_blank(),
      # legend.position = "top",
      # legend.justification = "left",
      plot.title = element_text(size = 16)
      # plot.subtitle = element_text(size = 14)
    ) 

ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2026/ens/lic_by_county.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r}
df |>
  filter(PROVINCE == "NS" & COUNTY %in% c(ens_counties)) |>
  filter(!(RIVERNAME_CLEANED == "AVON")) |> 
  mutate(
    RIVERNAME_CLEANED = if_else(RIVERNAME_CLEANED == "SHUBENACADIE GRAND LAKE", "SHUBENACADIE", RIVERNAME_CLEANED),
    RIVER = case_when(
      str_detect(RIVERNAME_CLEANED, "SHUBENACADIE") ~ RIVERNAME_CLEANED,
      TRUE ~ "OTHER"
      ),
    RIVER = str_to_title(str_trim(RIVER))
    ) |> 
  group_by(YEAR, RIVER) |> 
  summarise(TOTAL = sum(FV_WEIGHT)) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  filter(YEAR %in% c(2015:2025)) |> 
  ggplot(aes(YEAR, TOTAL, fill = RIVER)) +
  geom_col(colour = "grey10", alpha = 0.8) +
  scale_y_continuous(
    n.breaks = 10,
    labels = scales::comma
    ) +
  scale_fill_viridis_d(direction = 1) +
  labs(
    title = "Reported gaspereau landings in Eastern NS", 
    #subtitle = "The 'other' for 2024 is Chezzetcook River",
    x = "", y = "Landings (kg)", fill = "River") +
  theme_bw() +
  theme(
      axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(size = 12),
      #axis.title.x = element_blank(),
      axis.title.y = element_text(size = 14),
      panel.grid = element_blank(),
      #panel.grid.minor = element_blank(),
      legend.background = element_blank(),
      # legend.position = "top",
      # legend.justification = "left",
      plot.title = element_text(size = 16)
      # plot.subtitle = element_text(size = 14)
    ) 

ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2026/ens/landings_ns_east.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r}
# Select data from Eastern NS. We remove AVON from the rivers as it is in West Hants
df |> 
  filter(PROVINCE == "NS") |> 
  mutate(
    AREA = case_when(
      COUNTY %in% c("COLCHESTER COUNTY", "CUMBERLAND COUNTY", "HALIFAX COUNTY", "HANTS COUNTY", "GUYSBOROUGH COUNTY") ~ "Eastern NS",
      COUNTY %in% c("RICHMOND COUNTY", "VICTORIA COUNTY", "CAPE BRETON COUNTY") ~ "Cape Breton",
      TRUE ~ "Western NS"
    ),
    YEAR = as.factor(YEAR)
  ) |> 
  filter(!(RIVERNAME_CLEANED == "AVON")) |> 
  #filter(AREA == "Cape Breton") |> 
  filter(AREA == "Eastern NS") |> 
  filter(YEAR == 2025) |> 
  mutate(DOY = make_date(year = 2025, month = month(FV_DATE_FISHED), day = day(FV_DATE_FISHED))) |> 
  group_by(DOY) |> 
  summarise(TOTAL = sum(FV_WEIGHT)) |> 
  ggplot(aes(DOY, TOTAL)) +
  geom_col(colour = "grey20", alpha = 0.8) +
  scale_y_continuous(labels = scales::comma, n.breaks = 10) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week") +
  theme_bw() +
  theme(
      axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 14),
      panel.grid = element_blank(),
      legend.background = element_blank(),
      plot.title = element_text(size = 16)
    ) +
  labs(y = "Reported Landings (kg)", x = "")

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/east_NS/landings_by_area.png", plot = landings_by_area, width = 6, height = 4, dpi = 300)

```

