# Setup
```{r library_etc, warning=FALSE}
# Library
library(tidyverse)
library(readxl)
library(ROracle)
library(flextable)

# Source alosa functions
source("~/git/ALOSA.functions/functions/sourcery.R")
sourcery()

# Here is the channel connection for when we haul things from the ALOSA db
channel <- dbConnect(
  DBI::dbDriver("Oracle"),
  username = "GASPEREA",
  password = "_REMOVED",
  "PTRAN",
  believeNRows = FALSE
  )

```

# Landings - QC data
```{r get_MARFIS_data, warning=FALSE}
# This is where we store the MARFIS pulls:
# R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata

# This function checks to see when the last pull was and asks if you'd like to
# update the pull. It then loads the MARFIS data without changing anything.
# If you decide to do a new MARFIS pull and there are new additions to the db
# that were not in the last pull, you will be prompted to make changes to the
# Master Rivername Database. This is located on the R drive here:'
# R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MASTER_RIVERNAME_DATABASE.csv
#source(here("other_functions", "pull_marfis_data.R"))

# You don't always have to pull the MARFIS data when working with it, that just
# updates the copy of the data we have to the most up to date version. If you 
# want to load MARFIS data that already exist, just load it from here:
load("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata")

# The function we use to clean the data is currently located here:

# "R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MARFIS.error.cleaner.R"

# This function contains data which CANNOT be stored on the unit github page
# because it contains information that ostensibly could be used to glean how
# much someone is earning, so we store it on the R drive, which seems a bit
# extra. However, this is the rule (for now)
source("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MARFIS_error_cleaner.R")

df <- marfis_error_cleaner(
  catch = catch,
  years = "all",
  convert_to_kgs = TRUE,
  tidy_data = TRUE,
  correct_eel_pot = TRUE,
  unknown_rivers_are_na = TRUE,
  unknown_gear_are_na = TRUE
  )

```

```{r}

df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    ) |> 
  ggplot(aes(YEAR, FV_WEIGHT)) +
  geom_col(fill = "#A2DBB5", colour = "grey10", alpha = 0.7) +
  theme_bw() +
  scale_y_continuous(n.breaks = 10, labels = scales::comma) +
  labs(
    title = "Total Reported Landings for Gaspereau in Queens / Lunenburg",
    subtitle = "n = number of licences reporting landings for each year",
    y = "Reported Landings (mt)",
    x = "Year"
    ) +
  theme(panel.grid = element_blank()) +
  geom_text(
    aes(label = paste0("n=", N)),
    vjust = -0.5,
    position = dodge,
    size = 3
    )

```

# LaHave plot
```{r, warning=FALSE, message=FALSE}
dodge <- position_dodge(width = 0.9)

df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(AREA = case_when(
    RIVERNAME_CLEANED == "LAHAVE" ~ "LAHAVE",
    RIVERNAME_CLEANED == "MEDWAY" ~ "MEDWAY",
    COUNTY == "QUEENS COUNTY" ~ "QUEENS",
    COUNTY == "LUNENBURG COUNTY" ~ "LUNENBURG",
    TRUE ~ COUNTY
  )) |> 
  # Re-assign the LaHave catch to Lunenburg on years where Lunenburg < 5
  mutate(
    AREA = if_else(
      YEAR %in% c(2021, 2025) & AREA == "LAHAVE",
      "LUNENBURG",
      AREA
    )
  ) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR, AREA) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    ) |> 
  #mutate(AREA = fct_reorder(AREA, FV_WEIGHT, .desc = TRUE)) |> 
  #mutate(AREA = fct_reorder(AREA, N, .fun = sum, .desc = TRUE)) |> 
  mutate(AREA = factor(AREA, levels = c("LUNENBURG", "LAHAVE", "MEDWAY", "QUEENS"))) |> 
  #I need to remove Lunenburg for 2021 and 2025 because n < 5
  #filter(!(AREA == "LUNENBURG" & YEAR == 2021 | AREA == "LUNENBURG" & YEAR == 2025)) |>
  #filter(!(AREA == "LUNENBURG" & YEAR %in% c(2016, 2017, 2018, 2021, 2025))) |>
  #filter(!(YEAR == 2021 | YEAR == 2025)) |> 
  ungroup() |>
  complete(AREA, YEAR, fill = list(FV_WEIGHT = 0, N = 0)) |>
  ggplot(aes(YEAR, FV_WEIGHT, fill = AREA)) +
  geom_col(colour = "grey10", alpha = 0.8, position = dodge) +
  theme_bw() +
  scale_y_continuous(n.breaks = 10, labels = scales::comma) +
  labs(
    title = "Total Reported Landings for Gaspereau in Queens / Lunenburg",
    subtitle = "n = number of licences reporting landings",
    y = "Reported Landings (mt)",
    x = "Year"
    ) +
  theme(panel.grid = element_blank()) +
  geom_text(
  aes(
    label = ifelse(N > 0, paste0("n=", N), NA),
    group = AREA
  ),
  vjust = -0.25,
  position = dodge,
  size = 2
)

ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2026/queens_lunenburg/landings_plot.png", plot = last_plot(), width = 6, height = 4, dpi = 300)


# Try assigning all Lahave catch as Lunenburg in 2021 and 2025
# i.e. if year == 2021 or 2025, LaHave = Gold River or lunenburg or something
```

# County plot
```{r, warning=FALSE, message=TRUE}
dodge <- position_dodge(width = 0.9)

df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(AREA = case_when(
    COUNTY == "QUEENS COUNTY" ~ "QUEENS",
    COUNTY == "LUNENBURG COUNTY" ~ "LUNENBURG",
    TRUE ~ COUNTY
  )) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR, AREA) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    ) |> 
  mutate(AREA = fct_reorder(AREA, FV_WEIGHT, .desc = TRUE)) |> 
  ungroup() |>
  complete(AREA, YEAR, fill = list(FV_WEIGHT = 0, N = 0)) |>
  ggplot(aes(YEAR, FV_WEIGHT, fill = AREA)) +
  geom_col(colour = "grey10", alpha = 0.8, position = dodge) +
  theme_bw() +
  scale_y_continuous(n.breaks = 10, labels = scales::comma) +
  labs(
    title = "Total Reported Landings for Gaspereau in Queens / Lunenburg",
    subtitle = "n = number of licences reporting landings for each year",
    y = "Reported Landings (mt)",
    x = "Year"
    ) +
  theme(panel.grid = element_blank()) +
  geom_text(
  aes(
    label = paste0("n=", N),
    group = AREA
    ),
  vjust = -0.25,
  position = dodge,
  size = 3
  )

```

```{r}
df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(AREA = case_when(
    RIVERNAME_CLEANED == "LAHAVE" ~ "LAHAVE",
    COUNTY == "QUEENS COUNTY" ~ "QUEENS",
    COUNTY == "LUNENBURG COUNTY" ~ "LUNENBURG",
    TRUE ~ COUNTY
  )) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR, AREA) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    )

```

```{r}
df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(AREA = case_when(
    COUNTY == "QUEENS COUNTY" ~ "QUEENS",
    COUNTY == "LUNENBURG COUNTY" ~ "LUNENBURG",
    TRUE ~ COUNTY
  )) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR, AREA) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    )

```

# Reporting rate
```{r}
read_xlsx("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Gaspereau Licences Area Project.xlsx") -> lics

lics |> 
  filter(`Licence Type Description (English)` == "NON-VESSEL BASED LIMITED") |> 
  #filter(Renewed == 2023) |> 
  select(LICENCE_ID = `Licence Id`, PROVINCE = `Province Abbrev (English)`, COUNTY_1 = `County Name 1`, COUNTY_2 = `County Name 2`) |> 
  filter(PROVINCE == "NS") |>
  filter(
    str_detect(COUNTY_1, "QUEENS|LUNENBURG") |
    str_detect(COUNTY_2, "QUEENS|LUNENBURG")
  ) |> 
  # This one shouldn't be in here, it is an NB licence
  filter(LICENCE_ID != 302402) |> 
  mutate(LICENCE_ID = as.factor(LICENCE_ID)) |> 
  distinct(LICENCE_ID) -> QL_lics

n_lics = length(QL_lics$LICENCE_ID)

# Licences reporting landings
df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(AREA = case_when(
    COUNTY == "QUEENS COUNTY" ~ "QUEENS",
    COUNTY == "LUNENBURG COUNTY" ~ "LUNENBURG",
    TRUE ~ NA_character_
  )) -> QL

QL |> 
  group_by(YEAR) |> 
  summarise(n = n_distinct(LICENCE_ID)) |>
  mutate(YEAR = as.factor(YEAR)) |> 
  select(YEAR, Landings = n) -> QL_lics_landings

# SWNB lics reporting DNF
didnotfish |> 
  filter(YEAR %in% 2020:2025, NIL_REPORT_FLAG == "Y") |> 
  semi_join(QL_lics, by = "LICENCE_ID") |> 
  group_by(YEAR) |> 
  count() |> 
  select(YEAR, DNF = n) -> QL_lics_dnf

# Bind them together
QL_lics_landings |> 
  inner_join(QL_lics_dnf, by = "YEAR") |> 
  mutate(Reporting = Landings + DNF) |> 
  mutate(Registered = n_lics, .after = Reporting) |> 
  mutate(DNR = Registered - Reporting, .before = Registered) |> 
  mutate(Rate = round(Reporting / Registered, 2)) |> 
  rename(Year = YEAR) |> 
  flextable() |> 
  autofit() |> 
  save_as_docx(path = "R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2026/queens_lunenburg/lics_table.docx")
  
```

```{r}
df |> 
  filter(PROVINCE == "NS") |> 
  filter(COUNTY == "LUNENBURG COUNTY" | COUNTY == "QUEENS COUNTY") |> 
  filter(YEAR >= 2020) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  group_by(YEAR, RIVERNAME_CLEANED) |> 
  summarise(
    FV_WEIGHT = round(sum(FV_WEIGHT)) / 1000,
    N = n_distinct(LICENCE_ID)
    )
```

