# Setup
```{r library_etc, warning=FALSE}
# Library
library(tidyverse)
library(readxl)
library(here)
library(ROracle)

# Source alosa functions
source(here("functions", "sourcery.R"))
sourcery()

# I use this function to quickly look at pertinent log data from the catch df
source(here("other_functions", "fwl.R"))

# This function plots landings for the licence
source(here("other_functions", "plot_licence.R"))

# Here is the channel connection for when we haul things from the ALOSA db
channel <- dbConnect(
  DBI::dbDriver("Oracle"),
  username = "GASPEREA",
  password = "gps983",
  "PTRAN",
  believeNRows = FALSE
  )
```

# Data - Load
```{r get_MARFIS_data}
# This is where we store the MARFIS pulls:
# R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata

# This function checks to see when the last pull was and asks if you'd like to
# update the pull. It then loads the MARFIS data without changing anything.
# If you decide to do a new MARFIS pull and there are new additions to the db
# that were not in the last pull, you will be prompted to make changes to the
# Master Rivername Database. This is located on the R drive here:'
# R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MASTER_RIVERNAME_DATABASE.csv
#source(here("other_functions", "pull_marfis_data.R"))

# You don't always have to pull the MARFIS data when working with it, that just
# updates the copy of the data we have to the most up to date version. If you 
# want to load MARFIS data that already exist, just load it from here:
load("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/Old pulls/marfis_pull.Rdata")
```

# Data - Cleaning
```{r, warning=FALSE}
# The function we use to clean the data is currently located here:

# "R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MARFIS.error.cleaner.R"

# This function contains data which CANNOT be stored on the unit github page
# because it contains information that ostensibly could be used to glean how
# much someone is earning, so we store it on the R drive, which seems a bit
# extra. However, this is the rule (for now)
source("R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/MARFIS_error_cleaner.R")

df <- marfis_error_cleaner(
  catch = catch,
  years = "all",
  convert_to_kgs = TRUE,
  tidy_data = TRUE,
  correct_eel_pot = TRUE,
  unknown_rivers_are_na = TRUE,
  unknown_gear_are_na = TRUE
  )

```

# Data - Landings
```{r}

# Get number of observations
df |> 
  filter(RIVERNAME_CLEANED == "TUSKET") |> 
  filter(YEAR %in% c(2020:2025)) |> 
  mutate(YEAR = as.factor(YEAR)) |>
  group_by(YEAR, LICENCE_ID) |> 
  summarise(TOTAL = sum(FV_WEIGHT)) |> 
  count() -> counts

df |> 
  filter(RIVERNAME_CLEANED == "TUSKET") |> 
  filter(YEAR %in% c(2020:2025)) |> 
  mutate(YEAR = as.factor(YEAR)) |>
  group_by(YEAR, LICENCE_ID) |> 
  summarise(TOTAL = sum(FV_WEIGHT)) |> 
  ggplot(aes(x = YEAR, y = TOTAL, fill = YEAR)) +
  geom_boxplot(alpha = 0.8, outliers = FALSE) +
  geom_jitter(pch = 21, width = 0.1, alpha = 0.8) +
  #geom_point() +
  # geom_text(
  #   data = counts,
  #   aes(x = YEAR, y = -1, label = paste0("n=", n)),
  #   vjust = 0,
  #   inherit.aes = FALSE
  # ) +
  coord_cartesian(clip = "off") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
    ) +
  scale_y_continuous(
    n.breaks = 10,
    labels = scales::comma
  ) +
  labs(
    title = "Reported landings for Tusket",
    x = "",
    y = "Total landings per licence (kg)",
    fill = "Year"
    ) +
  scale_fill_viridis_d()

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/landings_boxplot.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r, warning=FALSE}
df |> 
  filter(RIVERNAME_CLEANED == "TUSKET") |> 
  filter(YEAR %in% c(2023, 2024, 2025)) |> 
  mutate(YEAR = as.factor(YEAR)) |>
  # Make all dates in 2025 so they can plot on the same date axis, but we will
  # colour for YEAR later so we can tell them apart
  mutate(FV_DATE_FISHED = make_date(year = 2025, month = month(FV_DATE_FISHED), day = day(FV_DATE_FISHED))) |> 
  mutate(WEEK = floor_date(FV_DATE_FISHED, unit = "week")) |> 
  filter(FV_DATE_FISHED < date("2025-05-30")) |>
  group_by(YEAR, WEEK) |> 
  summarise(FV_WEIGHT = sum(FV_WEIGHT), .groups = "drop") |> 
  complete(YEAR, WEEK) |> 
  ggplot(aes(WEEK, FV_WEIGHT, fill = YEAR)) +
  geom_col(position = position_dodge(), colour = "grey20", alpha = 0.7) +
  scale_y_continuous(labels = scales::comma, n.breaks = 10) +
  labs(title = "Reported gaspereau landings for Tusket River", x = "", y = "Mass (kg)", fill = "Year") +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week")+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)
    ) +
  scale_fill_viridis_d()

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/landings_barplot.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

# Data - Age
```{r, warning=FALSE}
# Get fish measurements for Tusket
fish_meas <- dbReadTable(channel, "ALOSA_FISH_BIO_DATA")
fish_meas |> 
  filter(SITE_ID == 2) -> fish_meas

# Get fish ages for Tusket
fish_age <- dbReadTable(channel, "ALOSA_FISH_AGE_DATA")
fish_age |> 
  # Get fish measured at Lake Vaughan only
  filter(SITE_ID == 2) -> fish_age

fish_age |> 
  left_join(fish_meas, by = c("YEAR", "FISH_ID")) |> 
  select(YEAR, CURRENT_AGE, AGE_AT_FIRST_SPAWN, MON, DAY, SPECIES_ID, SEX_ID, FORK_LENGTH, WEIGHT) |> 
  mutate(DATE = make_date(year = YEAR, month = MON, day = DAY), .after = YEAR) |> 
  select(-MON, -DAY) |> 
  filter(!(SEX_ID == 3)) |> 
  mutate(
    SEX_ID = case_when(
      SEX_ID == 1 ~ "M",
      SEX_ID == 2 ~ "F",
      TRUE ~ NA
      )
  ) -> fish_df

fish_df |>
  #ggplot(aes(CURRENT_AGE, FORK_LENGTH, group = interaction(CURRENT_AGE, AGE_AT_FIRST_SPAWN))) +
  filter(CURRENT_AGE > 2) |> 
  ggplot(aes(CURRENT_AGE, FORK_LENGTH, group = interaction(CURRENT_AGE, SEX_ID), fill = SEX_ID)) +
  geom_boxplot(
    outlier.shape = 21,
    alpha = 0.8
    ) +
  scale_y_continuous(n.breaks = 10) +
  labs(
    title = "Age versus length for gasepreau measured at Lake Vaughan Dam",
    #subtitle = "DNR = Did Not Report; DNF = Did Not Fish; Y = Reported",
    x = "Current Age",
    y = "Fork length (cm)",
    fill = "Sex"
    ) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
    ) +
  scale_fill_viridis_d()  
  
```

```{r, warning=FALSE}
fish_df |>
  #ggplot(aes(CURRENT_AGE, FORK_LENGTH, group = interaction(CURRENT_AGE, AGE_AT_FIRST_SPAWN))) +
  filter(CURRENT_AGE > 2) |> 
  ggplot(aes(CURRENT_AGE, WEIGHT, group = interaction(CURRENT_AGE, SEX_ID), fill = SEX_ID)) +
  geom_boxplot(
    outlier.shape = 21,
    alpha = 0.8
    ) +
  scale_y_continuous(n.breaks = 10) +
  labs(
    title = "Age versus mass for gasepreau measured at Lake Vaughan Dam",
    #subtitle = "DNR = Did Not Report; DNF = Did Not Fish; Y = Reported",
    x = "Current Age",
    y = "Mass (grams)",
    fill = "Sex"
    ) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
    ) +
  scale_fill_viridis_d()
```

# Data - Escapement
```{r escapement_vd}
# Locate your CSV for counts
path_to_counts_CSV <- "C:/Users/graylo/OneDrive - DFO-MPO/Alosa/Counts/2025/Vaughan 2025 count data.csv"

# Run escapement script
escapement_vd <- onespecies.river.escapement(
  path_to_counts_CSV,
  fixtime = TRUE,
  downstream.migration = FALSE,
  database = FALSE,
  year = 2025,
  site = 2,
  channel = channel
)

# We want to add where the data are from
escapement_vd$location <- "Lake Vaughan"

escapement_vd  |> 
  mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> 
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) |> 
  mutate(date = make_date(2025, mon, day)) -> escapement_vd

#in_season_vd_escapement_plot <-
escapement_vd |> 
  ggplot(aes(date, total)) +
  geom_ribbon(
    aes(ymin = clow, ymax = chigh),
    fill = "#41B7C4",
    #colour = "#4BBAC3",
    alpha = 0.2
  ) +
  geom_path(
    colour = "grey50",
    alpha = 0.8,
    linewidth = 0.7
    ) +
  theme_bw() +
  labs(
    title = paste("Gaspereau escapement at Lake Vaughan in", 2025),
    subtitle = "Shading represents 95% confidence intervals",
    x = "Date",
    y = "Fish / day"
  ) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week") +
  scale_y_continuous(
    limits = c(0, max(escapement_vd$chigh, na.rm = TRUE)),
    breaks = seq(0, max(escapement_vd$chigh, na.rm = TRUE), by = 1e4),
    labels = scales::comma
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
      ),
    axis.title.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()
    )

# Save as a png for sharing
#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/escapement.png", plot = last_plot(), width = 6, height = 4, dpi = 300)
```

# Data - Blueback proportions (observed)
```{r}
# This takes the observations of species from the biocharacteristics data and 
# the supplementary observations (i.e. the ones just checking for species) and
# combines them to show how many BBs were actually observed for 2025
proportions <- split_species(
    year = 2025,
    siteID = 2,
    channel = channel
  )

# This shows the actual number of As and Bs we counted each day
proportions |>
  select(date, A, BB) |> 
  pivot_longer(cols = c(A, BB), values_to = "observed", names_to = "species") |> 
  ggplot(aes(date, observed, fill = species)) +
  geom_col(position = position_dodge())

# This shows them as proportions
proportions |>
  select(date, A, BB) |> 
  pivot_longer(cols = c(A, BB), values_to = "observed", names_to = "species") |> 
  ggplot(aes(date, observed, fill = species)) +
  geom_col(position = "fill", alpha = 0.7, colour = "grey20") +
  #theme_minimal() +
  labs(
    title = "Species proportions at Lake Vaughan Dam in 2025",
    y = "Percentage",
    fill = "Species"
  ) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week") +
  scale_y_continuous(breaks = seq(0, 1, 0.1), labels = scales::label_percent(accuracy = 1)) +
  scale_fill_viridis_d(labels = c("Alewife", "Blueback")) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
      ),
    axis.title.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.background = element_blank()
    )

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/blueback_proportions.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

# Data - Blueback proportions (imputed)
```{r}
# Proportions for 2024
proportions_2024 <- split_species(year = 2024, siteID = 2, channel = channel)
proportions_2024 <- padr::pad(proportions_2024, interval = "day") |> select(date, BBprop)
proportions_2024 <- imputeTS::na_interpolation(proportions_2024)
proportions_2024$mon<-month(proportions_2024$date)
proportions_2024$day<-day(proportions_2024$date)
#proportions_2024 |> ggplot(aes(date, BBprop)) + geom_path()

# Proportions for 2025
proportions_2025 <- split_species(year = 2025, siteID = 2, channel = channel)
proportions_2025 <- padr::pad(proportions_2025, interval = "day") |> select(date, BBprop)
proportions_2025 <- imputeTS::na_interpolation(proportions_2025)
proportions_2025$mon<-month(proportions_2025$date)
proportions_2025$day<-day(proportions_2025$date)
#proportions_2025 |> ggplot(aes(date, BBprop)) + geom_path()
```

```{r}
# We can also use the twospecies.river.escapement function to get the species
# splits, but this has the added benefit of calculating CIs. We use the 
# proportions df we made above in the function
species_df <- twospecies.river.escapement(
  filename = NULL,
  year = 2025,
  site = 2,
  channel = channel,
  species.split = proportions_2025
)

# Alewives
#species_df[[1]]

# Bluebacks
species_df[[2]] -> BB

# Deal with the NaNs so that the plot is good
BB |> 
    mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> 
    mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> BB

BB |>
  mutate(date = make_date(year = 2025, month = mon, day = day)) |> 
  ggplot(aes(date, total)) +
  geom_path(
    colour = "#7ECDBB",
    alpha = 0.9,
    linewidth = 1.25
    ) +
  geom_ribbon(
    aes(ymin = clow, ymax = chigh),
    fill = "#7ECDBB",
    alpha = 0.2
  ) +
  theme_minimal() +
  labs(
    title = paste0("Blueback escapement at Lake Vaughan Dam in ", 2025),
    x = "",
    y = "Fish / day"
  ) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 day") +
  scale_y_continuous(
    limits = c(0, max(BB$chigh)),
    breaks = seq(0, max(BB$chigh), by = 1e2),
    labels = scales::comma
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      vjust = 1,
      hjust = 1
      ),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()
    )

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/blueback_escapement.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r}
# Cumulative plot of BBs
BB_cumulative <- BB |> mutate(cumulative_total = cumsum(total))

BB_cumulative |> 
  mutate(date = make_date(year = 2025, month = mon, day = day)) |> 
  ggplot(aes(date, cumulative_total)) +
  geom_path(colour = "grey40", alpha = 0.8, linewidth = 1.75, na.rm = TRUE)+
  theme_bw() +
  labs(
    title = paste("Cumulative blueback escapement at Lake Vaughan Dam in", 2025),
    x = "",
    y = "Escapement"
  ) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 day") +
  scale_y_continuous(
    limits = c(0, max(BB_cumulative$cumulative_total)),
    breaks = seq(0, max(BB_cumulative$cumulative_total), 2e2),
    labels = scales::comma
  ) +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.key = element_blank()
  )

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/blueback_escapement_cumulative.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

```{r}
all_years_df |>
  group_by(year) |> 
  mutate(cumulative_total = cumsum(total)) -> all_years_BBs_cumulative 
  
all_years_BBs_cumulative |> 
  mutate(date = make_date(year = 2025, month = month(date), day = day(date))) |> 
  ggplot(aes(date, cumulative_total, colour = as.factor(year))) +
  geom_path(alpha = 1, linewidth = 1.4, na.rm = TRUE)+
  theme_bw() +
  labs(
    title = "Cumulative blueback escapement at Lake Vaughan Dam",
    x = "Date",
    y = "Escapement",
    colour = "Year"
  ) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 week", limits = as.Date(c("2025-05-19", NA))) +
  scale_y_continuous(
    #limits = c(0, max(all_years_BBs_cumulative$cumulative_total)),
    breaks = seq(0, max(all_years_BBs_cumulative$cumulative_total * 1.2), 2e3),
    labels = scales::comma
  ) +
  theme_minimal()+
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.background = element_blank(),
    #plot.background = element_rect(fill = "grey95"),
    legend.key = element_blank()
  ) +
  guides(colour = guide_legend(override.aes = list(linewidth = 2))) +
  scale_color_viridis_d(direction = 1)

#ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/blueback_cumulative_past_years.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

# Data - Exploitation 2025
```{r}
# These are data from when George and Mark inspected catches of bags of 100 fish
# on the Tusket for alewife vs blueback in 2022. We will use them to infer the
# proportions of catch for each species and change the proportion with date
readxl::read_xlsx(
  "R:/Science/Population Ecology Division/DFD/Alosa/Locations/Tusket River/Tusket 2022/Data Sheets/2022 Yarmouth County Catch Inspection.xlsx",
  sheet = "Sheet1"
  ) |> 
  mutate(date = make_date(year = year, month = mon, day = day)) -> inspection

# Our first detected blueback herring for 2025 was on May 30th. If we assume
# that the fish takes 7 days to get from the mouth of the river to the dam, then
# the fish are exposed to the different gear types as follows based on previous
# estimates of migration behaviour in the Tusket:
# Gill netters: May 30 - 7 = May 23
# Dip netters:  May 30 - 3 = May 27

# First we must parse out the proportions observed for each gear type from
# the inspection in 2022.
# Gill netters = 0.03
# Dip netters = 0
inspection |> 
  filter(date >= date("2022-05-20") & method == "gill" & river == "Tusket") |> 
  summarize(BBprop = sum(n.blueback) / sum(n.alewife)) -> gill_netters_proportion

inspection |> 
  filter(date >= date("2022-05-20") & method == "dip" & river == "Tusket") |> 
  summarize(BBprop = sum(n.blueback) / sum(n.alewife)) -> dip_netters_proportion

# Get the total catch (in number of fish) for Tusket for 2025
df |>
  filter(YEAR == 2025 & RIVERNAME_CLEANED == "TUSKET") |> 
  summarise(total_catch = sum(FV_WEIGHT) / .240) -> tusket_total_catch

# Since the dip netters had no bluebacks in their catch (i.e. their proportion is 0),
# only the gill netters have to have their catch portioned into BB and alewife
df |> filter(YEAR == 2025 & RIVERNAME_CLEANED == "TUSKET" & GEAR_DESCRIPTION == "GILL NET (SET OR FIXED)") |> as_tibble() -> tusket_gill

tusket_gill |> 
  # This date is first detection of BBs minus seven days i.e. May 30 - 7 = May 23
  filter(FV_DATE_FISHED >= date("2025-05-23")) |> 
  summarise(N_CAUGHT = sum(FV_WEIGHT) / 0.24) |> 
  mutate(BB_CAUGHT = N_CAUGHT * gill_netters_proportion$BBprop) -> bluebacks_caught_2025

# Calculate the BB ER by taking the number we estimate to have been caught
# (in this case it was only by gill netters) and divide it by the total number
# of bluebacks estimated to have escaped.
bluebacks_escaped_2025 <- sum(as.data.frame(species_df[[2]])["total"])
blueback_exploitation_2025 <- bluebacks_caught_2025$BB_CAUGHT / ( bluebacks_escaped_2025+ bluebacks_caught_2025$BB_CAUGHT)

# Grab alewife exploitation
df |>
  filter(RIVERNAME_CLEANED == "TUSKET" & YEAR == 2025) |> summarise(N_CAUGHT = sum(FV_WEIGHT) / 0.24) |> 
  mutate(ALEWIFE_CAUGHT = N_CAUGHT - bluebacks_caught_2025$BB_CAUGHT) |> 
  mutate(ALEWIFE_ESCAPED = sum(as.data.frame(species_df[1])["total"])) |> 
  mutate(ALEWIFE_ER = ALEWIFE_CAUGHT / (ALEWIFE_ESCAPED + ALEWIFE_CAUGHT)) -> alewife_2025_df

# Combine everything into a table
exploitation_2025 <- tibble(
  species = c("Alewife", "Blueback"),
  year = c(2025, 2025),
  escaped = c(alewife_2025_df$ALEWIFE_ESCAPED, bluebacks_escaped_2025),
  caught = c(alewife_2025_df$ALEWIFE_CAUGHT, bluebacks_caught_2025$BB_CAUGHT),
  exploitation_rate = c(alewife_2025_df$ALEWIFE_ER, blueback_exploitation_2025)
)

exploitation_2025 <- exploitation_2025 |> 
  summarise(escaped = sum(escaped), caught = sum(caught)) |> 
  mutate(exploitation_rate = caught / (caught + escaped)) |> 
  mutate(species = "All", year = 2025) |> 
  bind_rows(exploitation_2025) |> 
  mutate(escaped = round(escaped), caught = round(caught), exploitation_rate = round(exploitation_rate, 2)) |> 
  select(species, year, escaped, caught, exploitation_rate)

```

# Data - Exploitation 2024
```{r}
# This is the same procedure we did above but for 2024
species_df_2024_vd <- twospecies.river.escapement(filename = NULL, year = 2024, site = 2, channel = channel, species.split = proportions)
species_df_2024_ph <- twospecies.river.escapement(filename = NULL, year = 2024, site = 14, channel = channel, species.split = proportions)

# Get the total catch (in number of fish) for Tusket for 2024
df |>
  filter(YEAR == 2024 & RIVERNAME_CLEANED == "TUSKET") |> 
  summarise(total_catch = sum(FV_WEIGHT) / .24) -> tusket_total_catch_2024

# Since the dip netters had no bluebacks in their catch in 2022 
# (i.e. their proportion is 0) only the gill netters have to have their catch
# portioned into BB and alewife. This is a silly assumption, but these are the
# only data we have.
df |> filter(YEAR == 2024 & RIVERNAME_CLEANED == "TUSKET" & GEAR_DESCRIPTION == "GILL NET (SET OR FIXED)") |> as_tibble() -> tusket_gill_2024

# Since bluebacks appeared earlier in 2024 relative to 2025, we need to calculate
# two values for the blueback proprtions based on which weekend they were observed.
inspection |> 
  filter(
    date >= "2022-05-13" &
    date <= "2022-05-15" &
    method == "gill" &
    river == "Tusket") |> 
  summarize(BBprop = sum(n.blueback) / sum(n.alewife)) -> may_13_2022_prop

inspection |>
  filter(
    date >= "2022-05-20" &
    date <= "2022-05-22" &
    method == "gill" &
    river == "Tusket"
    ) |> 
  summarize(BBprop = sum(n.blueback) / sum(n.alewife)) -> may_20_2022_prop

# Our first detection of a BB in 2024 was on May 23, so May 23 - 7 = May 16
tusket_gill_2024 |> 
  filter(FV_DATE_FISHED >= date("2024-05-16") & FV_DATE_FISHED < date("2025-05-20")) |> 
  summarise(N_CAUGHT = sum(FV_WEIGHT) / 0.24) |> 
  mutate(BB_CAUGHT = N_CAUGHT * may_13_2022_prop$BBprop) -> bluebacks_caught_2024_week1

tusket_gill_2024 |> 
  filter(FV_DATE_FISHED >= date("2024-05-20")) |> 
  summarise(N_CAUGHT = sum(FV_WEIGHT) / 0.24) |> 
  mutate(BB_CAUGHT = N_CAUGHT * may_20_2022_prop$BBprop) -> bluebacks_caught_2024_week2

rbind(bluebacks_caught_2024_week1, bluebacks_caught_2024_week2) |> 
  summarise(BB_CAUGHT = sum(BB_CAUGHT)) -> bluebacks_caught_2024

# Calculate the BB ER by taking the number we estimate to have been caught
# (in this case it was only by gill netters) and divide it by the total number
# of bluebacks estimated to have escaped.
bluebacks_escaped_2024 <- sum(sum(as.data.frame(species_df_2024_vd[2])["total"]), sum(as.data.frame(species_df_2024_ph[2])["total"]))
blueback_exploitation_2024 <- bluebacks_caught_2024$BB_CAUGHT / (bluebacks_escaped_2024 + bluebacks_caught_2024$BB_CAUGHT)

# Grab alewife exploitation
df |>
  filter(RIVERNAME_CLEANED == "TUSKET" & YEAR == 2024) |> summarise(N_CAUGHT = sum(FV_WEIGHT) / 0.24) |> 
  mutate(ALEWIFE_CAUGHT = N_CAUGHT - bluebacks_caught_2024$BB_CAUGHT) |> 
  # Need to get the fish from both VD and PH sites for 2024
  mutate(ALEWIFE_ESCAPED = sum(sum(as.data.frame(species_df_2024_vd[1])["total"]), sum(as.data.frame(species_df_2024_ph[1])["total"]))) |> 
  mutate(ALEWIFE_ER = ALEWIFE_CAUGHT / (ALEWIFE_ESCAPED + ALEWIFE_CAUGHT)) -> alewife_2024_df

# Combine everything into a table
exploitation_2024 <- tibble(
  species = c("Alewife", "Blueback"),
  year = c(2024, 2024),
  escaped = c(alewife_2024_df$ALEWIFE_ESCAPED, bluebacks_escaped_2024),
  caught = c(alewife_2024_df$ALEWIFE_CAUGHT, bluebacks_caught_2024$BB_CAUGHT),
  exploitation_rate = c(alewife_2024_df$ALEWIFE_ER, blueback_exploitation_2024)
)

exploitation_2024 <- exploitation_2024 |> 
  summarise(escaped = sum(escaped), caught = sum(caught)) |> 
  mutate(exploitation_rate = caught / (caught + escaped)) |> 
  mutate(species = "All", year = 2024) |> 
  bind_rows(exploitation_2024) |> 
  mutate(escaped = round(escaped), caught = round(caught), exploitation_rate = round(exploitation_rate, 2)) |> 
  select(species, year, escaped, caught, exploitation_rate)
```

# Data - Summary Document Table 1
```{r}
rbind(exploitation_2024, exploitation_2025)
```

# Data - Export data for daily counts all years CSV
```{r}
# 2025 - Just VD
proportions_2025 <- split_species(year = 2025, siteID = 2, channel = channel)
escapement_2025 <- twospecies.river.escapement(filename = NULL, year = 2025, site = 2, channel = channel, species.split = proportions_2025)
escapement_2025_A <- as.data.frame(escapement_2025[1])
escapement_2025_B <- as.data.frame(escapement_2025[2])
escapement_2025_A |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2025_A
escapement_2025_B |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2025_B

bind_rows(escapement_2025_A, escapement_2025_B) |> 
  select(-dayofyear) |> 
  group_by(mon, day) |> 
  summarise(across(where(is.numeric), sum, na.rm = TRUE), .groups = "drop") -> escapement_2025_All

# 2024 - we need PH + VD
proportions_2024 <- split_species(year = 2024, siteID = 2, channel = channel)
escapement_2024_vd <- twospecies.river.escapement(filename = NULL, year = 2024, site = 2, channel = channel, species.split = proportions_2024)
escapement_2024_ph <- twospecies.river.escapement(filename = NULL, year = 2024, site = 14, channel = channel, species.split = proportions_2024)
escapement_2024_vd_A <- as.data.frame(escapement_2024_vd[1])
escapement_2024_vd_B <- as.data.frame(escapement_2024_vd[2])
escapement_2024_ph_A <- as.data.frame(escapement_2024_ph[1])
escapement_2024_ph_B <- as.data.frame(escapement_2024_ph[2])
escapement_2024_vd_A |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2024_vd_A
escapement_2024_vd_B |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2024_vd_B
escapement_2024_ph_A |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2024_ph_A
escapement_2024_ph_B |> mutate(across(everything(), ~ ifelse(is.nan(.), 0, .))) |> mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) -> escapement_2024_ph_B

bind_rows(escapement_2024_vd_A, escapement_2024_ph_A) |> 
  select(-dayofyear) |>
  group_by(mon, day) |>
  summarise(across(where(is.numeric), sum, na.rm = TRUE), .groups = "drop") |>
  mutate(year = 2024, species = "A", river = "Tusket") |> 
  select(month, day, year, species, number = total, river) ->
  escapement_2024_A

bind_rows(escapement_2024_vd_B, escapement_2024_vd_B) |> select(-dayofyear) |> group_by(mon, day) |> summarise(across(where(is.numeric), sum, na.rm = TRUE), .groups = "drop") -> escapement_2024_B

bind_rows(escapement_2024_A, escapement_2024_B) |> group_by(mon, day) |> summarise(across(where(is.numeric), sum, na.rm = TRUE), .groups = "drop") -> escapement_2024_All

# Export the data
write.csv(escapement_2025_A, "C:/Users/graylo/Documents/data/escapement_2025_A.csv")
```

# Data - Reporting
```{r}
# New data from licencing
licences <- read_excel(path = "R:/Science/Population Ecology Division/DFD/Alosa/MARFISSCI/LA1040- Gaspereau Licences WITH SITE LOCATIONS 2024.xlsx", sheet = 1)

# Get all the licences that have ever reported for Tusket
df |> 
  #filter(YEAR %in% c(2020:2025)) |> 
  filter(RIVERNAME_CLEANED == "TUSKET") |> 
  distinct(LICENCE_ID, YEAR) |> 
  arrange(YEAR, LICENCE_ID) |> 
  select(YEAR, LICENCE_ID) |> 
  mutate(YEAR = as.factor(YEAR)) |> 
  mutate(REPORT_FLAG = "Y") -> tusket_fished

# Get all the licences that have ever reported DNF that appear in the list of 
# licences in the licences that have fished the tusket
didnotfish |> 
  filter(LICENCE_ID %in% tusket_fished$LICENCE_ID) |> 
  filter(NIL_REPORT_FLAG == "Y") -> tusket_dnf

# The following code creates a table that shows information we have on all licences
# that have ever reported catch or didnotfish on the Tusket since 2008. This 
# table will contian NAs where no information was recieved i.e. a "DNR" for 
# that year
tusket_fished |> 
  full_join(tusket_dnf) |> 
  # I am going to remove these records that have contradictory reporting for now
  # so we can get some estimate of licences fishing (n is only = 7).
  # Need to replace NA with N
  mutate(
    REPORT_FLAG = coalesce(REPORT_FLAG, "N"),
    NIL_REPORT_FLAG = coalesce(NIL_REPORT_FLAG, "N")
  ) |> 
  filter(!(REPORT_FLAG == "Y" & NIL_REPORT_FLAG == "Y")) |> 
  # Now that we have taken care of the instances where there were contradictory
  # entries, we can take one of these columns (they are the opposite of one
  # another) and use it to create a new column that shows us who reported
  select(YEAR, LICENCE_ID, REPORT_FLAG) |> 
  mutate(
    REPORT_FLAG = case_when(
      REPORT_FLAG == "N" ~ "DNF",
      TRUE ~ REPORT_FLAG
      )
  ) |> 
  # We need to add a function here (unique) to tell pivot_Wider to grab the first value
  # from the list as it creates a list when we have two character variables
  pivot_wider(names_from = YEAR, values_from = REPORT_FLAG, values_fn = unique) |> 
  arrange(LICENCE_ID) |> 
  mutate(
    across(everything(), ~ replace_na(., "DNR"))
  ) -> licence_table

#writexl::write_xlsx(licence_table, path = "C:/Users/graylo/Documents/tusket_reporting.xlsx")

# Make a plot showing the number of different responses for each year
licence_table |>
  pivot_longer(cols = -LICENCE_ID, names_to = "YEAR", values_to = "FISHED") |> 
  # mutate(FISHED = if_else(is.na(FISHED), "DNR", FISHED)) |> 
  # mutate(FISHED = if_else(FISHED == "N", "DNF", FISHED)) |> 
  mutate(FISHED = fct_relevel(FISHED, "DNR", "DNF", "Y")) |> 
  group_by(YEAR) |> 
  count(FISHED) |> 
  ggplot(aes(YEAR, n, fill = FISHED)) +
  geom_col(position = "stack", alpha = 0.7, colour = "grey20") +
  scale_y_continuous(n.breaks = 10) +
  labs(
    title = paste0("Reporting rates for licences on the Tusket River (as of ", paste(month(Sys.Date(), label = TRUE), year(Sys.Date())), ")"),
    #subtitle = "DNR = Did Not Report; DNF = Did Not Fish; Y = Reported",
    x = "",
    y = "Count",
    fill = "Reported?"
    ) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)
    ) +
  scale_fill_viridis_d()

ggsave("R:/Science/Population Ecology Division/DFD/Alosa/Assessment Results/Advisory Meetings/2025/yar-shel/reporting_rate.png", plot = last_plot(), width = 6, height = 4, dpi = 300)

```

# Data - Catch curve
```{r, warning=FALSE}
# Make a grid to hold the combinations of ages and spawnings
# Note, fish spawning for the first time have a spawnings value = 0
data <- expand.grid(current_age = 2:9, previous_spawnings = 0:5, year = c(2019, 2021, 2022, 2024))
data$age_at_first_spawn <- data$current_age - data$previous_spawnings
data <- tibble(data)
data <- data |> filter(age_at_first_spawn > 1) |> arrange(year, current_age, age_at_first_spawn) |> relocate(year)
data
```

```{r}
# Now we need to aggregate the age data by year. Years 2019, 2022, and 2022 are
# currently on the db
tusket_age <- dbReadTable(channel, "ALOSA_FISH_AGE_DATA") |> filter(SITE_ID == 2)

# Bring in data from the R drive that is not in the db
tusket_2024 <- read_csv("R:/Science/Population Ecology Division/DFD/Alosa/Locations/Tusket River/Tusket 2024/Data Sheets/Lily_aged_TUSKET_2024.csv")
tusket_2024 <- tusket_2024 |> select(year, current_age = current.age, age_at_first_spawn = age.at.first.spawn)
tusket_2024$previous_spawnings <- tusket_2024$current_age - tusket_2024$age_at_first_spawn
tusket_2024 <- tusket_2024 |> filter(age_at_first_spawn > 1) |> arrange(year, current_age, age_at_first_spawn) |> relocate(year)

# Count the data
tusket_age |>
  #filter(YEAR == 2022) |>
  mutate(previous_spawnings = CURRENT_AGE - AGE_AT_FIRST_SPAWN) |> 
  select(year = YEAR, current_age = CURRENT_AGE, age_at_first_spawn = AGE_AT_FIRST_SPAWN, previous_spawnings) |> 
  rbind(tusket_2024) |> 
  group_by(year, previous_spawnings, age_at_first_spawn) |> 
  count() -> tusket_data_sums

# Calculate the catch curve across multiple years
years <- c(2019, 2021, 2022, 2024)
mortality_df <- data.frame(
  year = numeric(),
  Z = numeric(),
  Z_lo = numeric(),
  Z_hi = numeric(),
  S = numeric(),
  mort_prop = numeric()
  )

for (year in years) {
  mod <- glm(n ~ previous_spawnings + as.factor(age_at_first_spawn), family = "poisson", data = tusket_data_sums |> filter(year == !!year))
  # This is our instantaneous mortality rate
  Z <- mod$coefficients["previous_spawnings"]
  Z_ci <- confint(mod)["previous_spawnings", ]
  Z_lo <- Z_ci[2]
  Z_hi <- Z_ci[1]
  # Survival (proportion) per spawning event
  S <- exp(mod$coefficients["previous_spawnings"])
  # Mortality (proportion) per spawning event
  mort_prop <- 1 - S
  mortality_df <- bind_rows(mortality_df, data.frame(year = year, Z = Z, Z_lo = Z_lo, Z_hi = Z_hi, S = S, mort_prop = mort_prop))
  }

mortality_df <- tibble(mortality_df)

# Exploitation Rates from previous years
# We will bring these in and hard code them to make things easier. These values
# come from the Tusket River 2025 Assessment Summary pdf and are the ER for
# 2019, 2021, 2022, and 2024, respectively. Because the mathematicians said so,
# we can get instantaneous natural mortality (M) from the catch equations when
# we know Z and F. We get F when we have ER from the following equation:
# F = ER * Z / (1 - exp(-Z)) where (1 - exp(-Z)) = mort_prop
# Once we have F, we can get M from the following equation:
# M = Z * (1 - (ER / (1 - exp(-Z))))

mortality_df |> 
  mutate(
    ER = c(0.51, 0.38, 0.44, 0.45),
    F = -log(1-ER),
    M = -Z - F
  ) -> mortality_df
    
mortality_df |> 
  pivot_longer(cols = c(Z, M, F), names_to = "type", values_to = "value") |> 
  ggplot(aes(year, y = abs(value), fill = type)) +
  geom_point(size = 3, pch = 21, alpha = 0.8) +
  labs(x = "", y = "") +
  scale_fill_viridis_d() +
  scale_y_continuous(limits = c(0, 2), breaks = seq(0, 2, 0.2)) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank())

# We have fishing mortality (F) in the form of the exploitation rate (ER) from
# comparing landings data to escapement. To get natural mortality (M) we need:
# Z = F + M i.e. mort = ER + M, therefore M = mort - ER
# I need grab previous ERs and calculate ER for 2025 to get a table of M
# Previous ERs: 2019 = 0.51, 2021 = 0.38, 2022 = 0.44, 2023 = 0.43, 2024 = 0.45
# Is ER in the correct form to subtract from instantaneous mortality?
# F = mort * ER / (1 - exp(mort))

```



